### ISSUE TITLE
PPA repository not up to date

### ISSUE THREAD

**Issue by russss** [JeremyGrosser/tablesnap#41]
The [PPA repository](https://launchpad.net/~synack/+archive/tablesnap) mentioned in the README is out of date - the most recent version of tablesnap available on there is from 2012-11-07. 

If it's not easy to keep the PPA up to date, I'd suggest removing the references to it.

**Comment by JeremyGrosser** [comment]
The PPA has been updated to 0.7.3.

**Comment by lanejlanej** [comment]
Any chance of updating PPA repository to 1.0.3?
