### ISSUE TITLE
Limit bandwidth of tablesnap

### ISSUE THREAD

**Issue by Itxaka** [JeremyGrosser/tablesnap#46]
Would be really helpful to be able to limit the tablesnap upload bandwidth, so in the case of using it on a production machine which needs to prioritise the out bandwidth from cassandra, tablesnap does not take as much bandwidth as possible.

**Comment by pcn** [comment]
Have you looked at the trickle library? http://monkey.org/~marius/pages/?page=trickle

**Comment by JeremyGrosser** [comment]
This isn't something that can be easily implemented within tablesnap. @pcn's suggestion of trickle or some tc (http://tldp.org/HOWTO/Traffic-Control-HOWTO/intro.html) rules are likely your best bet.
