### ISSUE TITLE
Seg fault in Docker on CoreOs

### ISSUE THREAD

**Issue by ppontryagin** [JeremyGrosser/tablesnap#61]
When running on CoreOs in Docker container I get 
```Segmentation fault (core dumped)```
Is it supposed to work in this environment?

**Comment by JeremyGrosser** [comment]
I don't think anybody's ever tested on CoreOS (aside from you, of course). Assuming there's nothing weird about your python binaries, the only thing I can think of that would cause this is some weirdness with inotify. Can you provide the core file, the output of dmesg, and the output of uname -a?

**Comment by ppontryagin** [comment]
Switched Ubuntu, problem is gone. It seems like problems with inotify. 
Will use it with Ubuntu :)
Anyway, thank you.
