### ISSUE TITLE
Tablesnap puts AWS keys in the processlist, give option to set via environment variables.

### ISSUE THREAD

**Issue by jwojcik** [JeremyGrosser/tablesnap#63]
Give an option to set AWS keys as environment variables rather than setting them as arguments so the keys don't show up in the process list.

Variable names are:
AWS_KEY
AWS_SECRET

**Comment by JeremyGrosser** [comment]
You can use AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for this already.
